### ISSUE TITLE
Hanging during login on asp.net core running in linux docker container

### ISSUE THREAD

**Issue by themicster** [alexforster/AmiClient#1]
Actually this doesn't seem to have anything to do with docker or linux. The client works fine when I run the debug build but the release build it hangs on login. I was seeing a similar hang with AsterNET as well. I am starting to think that .net core release build has some issue with network streams.

Here is the output:
In: Asterisk Call Manager/3.2.0
Out: Action: Challenge
ActionID: b9e3e647-1c13-4095-8319-13638ef61c5d
AuthType: MD5

In: Response: Success
ActionID: b9e3e647-1c13-4095-8319-13638ef61c5d
Challenge: 119804922

**Comment by alexforster** [comment]
@themicster were you able to get past this? Sorry, I just realized I wasn't watching my own repository so I never saw this!

**Comment by themicster** [comment]
The problem I found with AsterNET was that it was looking for '\n' instead of "\n" which could mean different things on different platforms.

**Comment by alexforster** [comment]
Oh yeah, just like with HTTP asterisk always terminates lines with `\r\n`. With my library, did you see similar behavior that you did before AsterNET fixed the char/string issue? I just use `ReadLine()` which I had hoped would consume `\r|\n|\r\n` but maybe that isn't the case...

**Comment by themicster** [comment]
It behaved like exactly the same problem, but I didn't dig enough to confirm, so it could be something else.  It could be the ReadLine when running on linux looks for a different line ending.

**Comment by alexforster** [comment]
Ack. Just in case I'll start splitting by `Byte[]{0x0d, 0x0a}` instead.

**Comment by alexforster** [comment]
Fixed in v1.1.0
