### ISSUE TITLE
DataReceived not firing

### ISSUE THREAD

**Issue by Ravenheart** [alexforster/AmiClient#16]
After the initial events for login come in, no more events ever get fired, such as when a new call comes or someone hangs up.

**Comment by futtie** [comment]
The buffer size in AmiClient.cs LineObserver() is too small for some groups of events. Set it to 8k and it will work for a while. Best solution would be to include the reading part in the while loop.

**Comment by Spacefish** [comment]
Look whether you have 100% cpu usage, if yes #17  might fix it.
