### ISSUE TITLE
Nuget package hangs on Login

### ISSUE THREAD

**Issue by geext-dk** [alexforster/AmiClient#6]
Hi again.
Looks like your latest (1.2.3) nuget package hangs when trying to login. I don't know how to debug this, but it works when I clone your repo and add reference to it in my solution.

**Comment by alexforster** [comment]
Uh oh, ack. I'll check it out asap. I'm going to unpublish the latest version until I figure out what's up.

**Comment by alexforster** [comment]
I'm not able to reproduce. Do you see any output if you wire up the `DataSent`/`DataReceived` events?

```csharp
client.DataSent += async (s, e) => await Console.Error.WriteAsync(Encoding.UTF8.GetString(e.Data));
client.DataReceived += async (s, e) => await Console.Error.WriteAsync(Encoding.UTF8.GetString(e.Data));
```

**Comment by alexforster** [comment]
Please reopen if you are still having problems.

**Comment by geext-dk** [comment]
Yeah. Sorry for not answering. 

> I'm not able to reproduce. Do you see any output if you wire up the `DataSent`/`DataReceived` events?
> 
> ```cs
> client.DataSent += async (s, e) => await Console.Error.WriteAsync(Encoding.UTF8.GetString(e.Data));
> client.DataReceived += async (s, e) => await Console.Error.WriteAsync(Encoding.UTF8.GetString(e.Data));
> ```
It outputs the event it tries to send to connect, but no response.

I would blame the emulator used by the server I try to connect, but if I download your project and ref to it in .csproj, all is ok.

**Comment by geext-dk** [comment]
![image](https://user-images.githubusercontent.com/46246344/58235206-04e96500-7d49-11e9-9326-a51e56c20080.png)
Simple example
with nuget it just hangs on login
after 'dotnet package remove AmiClient && dotnet add reference ../AmiClient' works perfectly

**Comment by alexforster** [comment]
Can you reproduce the problem using your local copy if you build/run in release mode?

**Comment by geext-dk** [comment]
I compiled both Debug and Release versions with `dotnet publish -c Debug` and `dotnet publish -c Release`, and both are working fine.
Then I immediately replaced the reference to local AmiClient project to the nuget package and did the same - both don't work.

**Comment by geext-dk** [comment]
Well, I don't know why but I've built the nuget package locally, installed it and it works just fine. But I needed to change one the .csproj . There is a property <IsPackable> set to "false". The package only builds if I remove the property

**Comment by alexforster** [comment]
I was actually building and publishing these using the `nuget` cli and metadata from the `AmiClient.nuspec` file. Since I strongly suspect that this is a tooling issue rather than a code issue, I've just published a new version which is identical to the previous version except created using `dotnet build` and metadata from the `AmiClient.csproj` file.

**Comment by Spacefish** [comment]
Probably related to #17  at least that fixed random hangs for me.
